dev:
  mongo:
    connectionString : "mongodb://root:155202Asd...@localhost:27017"
    database :  "GoDocumentDb"
    collection : {"document" : "Documents"}
  jwtKey:
    secretKey : "serkanapisecretkey"
  userService:
    name: "UserService"
    baseUrl: "http://localhost:9000/"